/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedCareerGapRouteImport } from './routes/_authenticated/career-gap'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedCalculaterRouteImport } from './routes/_authenticated/Calculater'
import { Route as AuthenticatedPrepJobIdRouteImport } from './routes/_authenticated/prep/$jobId'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'

const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareerGapRoute = AuthenticatedCareerGapRouteImport.update({
  id: '/career-gap',
  path: '/career-gap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculaterRoute = AuthenticatedCalculaterRouteImport.update({
  id: '/Calculater',
  path: '/Calculater',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrepJobIdRoute = AuthenticatedPrepJobIdRouteImport.update({
  id: '/prep/$jobId',
  path: '/prep/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/seed': typeof SeedRoute
  '/Calculater': typeof AuthenticatedCalculaterRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/career-gap': typeof AuthenticatedCareerGapRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/prep/$jobId': typeof AuthenticatedPrepJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/seed': typeof SeedRoute
  '/Calculater': typeof AuthenticatedCalculaterRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/career-gap': typeof AuthenticatedCareerGapRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/prep/$jobId': typeof AuthenticatedPrepJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/seed': typeof SeedRoute
  '/_authenticated/Calculater': typeof AuthenticatedCalculaterRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/career-gap': typeof AuthenticatedCareerGapRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/prep/$jobId': typeof AuthenticatedPrepJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/seed'
    | '/Calculater'
    | '/agent'
    | '/applications'
    | '/career-gap'
    | '/jobs'
    | '/notifications'
    | '/opportunities'
    | '/profile'
    | '/jobs/$id'
    | '/prep/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/seed'
    | '/Calculater'
    | '/agent'
    | '/applications'
    | '/career-gap'
    | '/jobs'
    | '/notifications'
    | '/opportunities'
    | '/profile'
    | '/jobs/$id'
    | '/prep/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/seed'
    | '/_authenticated/Calculater'
    | '/_authenticated/agent'
    | '/_authenticated/applications'
    | '/_authenticated/career-gap'
    | '/_authenticated/jobs'
    | '/_authenticated/notifications'
    | '/_authenticated/opportunities'
    | '/_authenticated/profile'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/prep/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SeedRoute: typeof SeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career-gap': {
      id: '/_authenticated/career-gap'
      path: '/career-gap'
      fullPath: '/career-gap'
      preLoaderRoute: typeof AuthenticatedCareerGapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Calculater': {
      id: '/_authenticated/Calculater'
      path: '/Calculater'
      fullPath: '/Calculater'
      preLoaderRoute: typeof AuthenticatedCalculaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep/$jobId': {
      id: '/_authenticated/prep/$jobId'
      path: '/prep/$jobId'
      fullPath: '/prep/$jobId'
      preLoaderRoute: typeof AuthenticatedPrepJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
  }
}

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalculaterRoute: typeof AuthenticatedCalculaterRoute
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedCareerGapRoute: typeof AuthenticatedCareerGapRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPrepJobIdRoute: typeof AuthenticatedPrepJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalculaterRoute: AuthenticatedCalculaterRoute,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedCareerGapRoute: AuthenticatedCareerGapRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPrepJobIdRoute: AuthenticatedPrepJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SeedRoute: SeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
